### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by evandrocoan** [Thom1729/Sublime-JS-Custom#31]
I just cloned it and got on console: (Sublime Text build 3174)
```
reloading plugin JSCustom.build_js_custom_syntaxes
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 183, in reload_plugin
    m.plugin_loaded()
  File "F:\SublimeText\Data\Packages\JSCustom\build_js_custom_syntaxes.py", line 19, in plugin_loaded
    old_configurations = get_configurations()
  File "F:\SublimeText\Data\Packages\JSCustom\build_js_custom_syntaxes.py", line 68, in get_configurations
    for name, config in SETTINGS.get('configurations').items()
AttributeError: 'NoneType' object has no attribute 'items'
reloading plugin JSCustom.jsx_close_tag_command
reloading plugin JSCustom.jsx_close_tag_listener
```

**Comment by Thom1729** [comment]
v1.0.14 should fix this. Please let me know if it doesn't!

**Comment by evandrocoan** [comment]
Thanks! Fixed.
