### ISSUE TITLE
Error while loading the plugin on startup

### ISSUE THREAD

**Issue by predragnikolic** [Thom1729/Sublime-JS-Custom#90]
sublime version: 4074

I wanted to try the typescript branch :) (master is also affected)
and I stumbled upon this:

```
reloading python 3.3 plugin GithubPR.OpenPackage
reloading python 3.3 plugin JSCustom.plugin
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 274, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/predrag/.config/sublime-text/Packages/JSCustom/plugin.py", line 12, in <module>
    from .src.commands.build_syntaxes import BuildJsCustomSyntaxCommand, BuildJsCustomSyntaxesCommand
  File "/home/predrag/.config/sublime-text/Packages/JSCustom/src/commands/build_syntaxes.py", line 3, in <module>
    from pathlib import Path
ImportError: No module named 'pathlib'
```

For some reason this JSCustom gets loaded with the python 3.3 version. (pathlib is available from version 3.4 and above)
but I can see in the .python-version file that this plugin should use version 3.8.

It is probably a ST issue, but before I reach out to them,
just wanted to check with you if you can maybe solve this?

**Comment by Thom1729** [comment]
The TypeScript support ought to be compatible with ST 3, so the pathlib dependency is a bug. I'll fix it and put out a new alpha.

**Comment by Thom1729** [comment]
Should be fixed in v2.4.0-alpha.3. Please let me know either way!

**Comment by predragnikolic** [comment]
Damn it :D 
```
  File "/home/predrag/.config/sublime-text/Packages/JSCustom/src/commands/build_tests.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named 'pathlib'
```
I wanted to do a PR, but it is just 2 lines. can you commit it? :)

After this change, there should be no errors

**Comment by Thom1729** [comment]
I left that one in place because that command is only used for testing — but of course that doesn't help if it's blowing up at import time. v2.4.0-alpha.4 should fix it properly.

**Comment by predragnikolic** [comment]
Well this issue hasn't lived long :)

Can confirm that the startup error is fixed
